Adds `header_info_size` variable to metadata
yunanwg/brilliant-CV pull request #77
Opened 2024-12-22 18:43 UTC by alexk101

Resolves #76

2025-01-20 14:42 UTC, yunanwg requested changes

2025-01-20 14:42 UTC, yunanwg commented on template/metadata.toml
> +        info_font_size = "8pt"
It would be nice if a comment could be placed above the new item.

2025-01-20 14:42 UTC, yunanwg commented on cv.typ
> +  let headerInfoFontSize = metadata.layout.header.info_font_size
For optional value, please use syntax like `metadata.layout.at("before_section_skip", default: 1pt)` with default value.

2025-01-22 20:52 UTC, alexk101 commented
Will try and resolve some of these issues soon

2025-01-22 21:32 UTC, yunanwg commented on cv.typ
> +  let headerInfoFontSize = metadata.layout.header.info_font_size
Here you will also need to add `eval` function, as font size is not string in typst but a special data type.

2025-01-22 21:33 UTC, yunanwg commented
Appreciated! I made a commit yesterday on your PR but don't know why it got lost somewhere. It should not be too complicated, tell me if you encounter any issue.

2025-02-15 19:49 UTC, yunanwg commented
I think there are some weird issues with this PR, as I cannot push any changes. Feel free to complete the PR or I will close it later on.

Thanks!

2025-02-16 19:15 UTC, merged